### ISSUE TITLE
[2.1 stable] Error when creating a pdf in the order list

### ISSUE THREAD

**Issue by netzarbeiter** [isotope/core#1053]
Create a document with the "Collection template" **iso_collection_default** chosen.
Go to the order list and click on the pdf icon and choose the document and press print.

```
Warning: getimagesize(isotope/c/cd-289809.jpg) [function.getimagesize]: failed to open stream: No such file or directory in system/modules/core/vendor/tcpdf/include/tcpdf_images.php on line 163
#0 [internal function]: __error(2, 'getimagesize(is...', '/isotope/...', 163, Array)
#1 system/modules/core/vendor/tcpdf/include/tcpdf_images.php(163): getimagesize('isotope/c/cd-28...')
#2 system/modules/core/vendor/tcpdf/tcpdf.php(6963): TCPDF_IMAGES::_parsejpeg('isotope/c/cd-28...')
#3 system/modules/core/vendor/tcpdf/tcpdf.php(18706): TCPDF->Image('isotope/c/cd-28...', 23.5866111111, 60.00625, 38.9466666667, 38.9466666667, '', '', 'B', false, 300, '', false, false, 0, false, false, true)
#4 system/modules/core/vendor/tcpdf/tcpdf.php(18116): TCPDF->openHTMLTagHandler(Array, 2, true)
#5 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#6 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(27.6281814815, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#7 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#8 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(178.529061111, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#9 system/modules/isotope/library/Isotope/Model/Document/Standard.php(115): TCPDF->writeHTML('
#0 [internal function]: __error(2, 'imagecreatefrom...', '/isotope/...', 6971, Array)
#1 system/modules/core/vendor/tcpdf/tcpdf.php(6971): imagecreatefromjpeg('isotope/c/cd-28...')
#2 system/modules/core/vendor/tcpdf/tcpdf.php(18706): TCPDF->Image('isotope/c/cd-28...', 23.5866111111, 60.00625, 38.9466666667, 38.9466666667, '', '', 'B', false, 300, '', false, false, 0, false, false, true)
#3 system/modules/core/vendor/tcpdf/tcpdf.php(18116): TCPDF->openHTMLTagHandler(Array, 2, true)
#4 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#5 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(27.6281814815, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#6 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#7 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(178.529061111, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#8 system/modules/isotope/library/Isotope/Model/Document/Standard.php(115): TCPDF->writeHTML('
#0 [internal function]: __error(2, 'imagejpeg() exp...', '/isotope/...', 148, Array)
#1 system/modules/core/vendor/tcpdf/include/tcpdf_images.php(148): imagejpeg(false, '/isotope/...', 75)
#2 system/modules/core/vendor/tcpdf/tcpdf.php(6987): TCPDF_IMAGES::_toJPEG(false, 75)
#3 system/modules/core/vendor/tcpdf/tcpdf.php(18706): TCPDF->Image('isotope/c/cd-28...', 23.5866111111, 60.00625, 38.9466666667, 38.9466666667, '', '', 'B', false, 300, '', false, false, 0, false, false, true)
#4 system/modules/core/vendor/tcpdf/tcpdf.php(18116): TCPDF->openHTMLTagHandler(Array, 2, true)
#5 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#6 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(27.6281814815, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#7 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#8 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(178.529061111, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#9 system/modules/isotope/library/Isotope/Model/Document/Standard.php(115): TCPDF->writeHTML('
#0 [internal function]: __error(2, 'imagedestroy() ...', '/isotope/...', 149, Array)
#1 system/modules/core/vendor/tcpdf/include/tcpdf_images.php(149): imagedestroy(false)
#2 system/modules/core/vendor/tcpdf/tcpdf.php(6987): TCPDF_IMAGES::_toJPEG(false, 75)
#3 system/modules/core/vendor/tcpdf/tcpdf.php(18706): TCPDF->Image('isotope/c/cd-28...', 23.5866111111, 60.00625, 38.9466666667, 38.9466666667, '', '', 'B', false, 300, '', false, false, 0, false, false, true)
#4 system/modules/core/vendor/tcpdf/tcpdf.php(18116): TCPDF->openHTMLTagHandler(Array, 2, true)
#5 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#6 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(27.6281814815, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#7 system/modules/core/vendor/tcpdf/tcpdf.php(5810): TCPDF->writeHTML('a:0:{...', true, false, true, true, '')
#8 system/modules/core/vendor/tcpdf/tcpdf.php(18048): TCPDF->MultiCell(178.529061111, 0, 'a:0:{...', false, '', false, 2, '', '', true, 0, true, true, 0, 'T', false)
#9 system/modules/isotope/library/Isotope/Model/Document/Standard.php(115): TCPDF->writeHTML('
#0 [internal function]: __error(2, 'Cannot modify h...', '/isotope/...', 7592, Array)
#1 system/modules/core/vendor/tcpdf/tcpdf.php(7592): header('Content-Descrip...')
#2 system/modules/isotope/library/Isotope/Model/Document/Standard.php(42): TCPDF->Output('rechnung_0011.p...', 'D')
#3 system/modules/isotope/library/Isotope/Backend/ProductCollection/Callback.php(346): Isotope\Model\Document\Standard->outputToBrowser(Object(Isotope\Model\ProductCollection\Order))
#4 system/modules/core/classes/Backend.php(279): Isotope\Backend\ProductCollection\Callback->printDocument(Object(Contao\DC_Table))
#5 contao/main.php(136): Contao\Backend->getBackendModule('iso_orders')
#6 contao/main.php(287): Main->run()
#7 {main}
TCPDF ERROR: Some data has already been output to browser, can't send PDF file
```

**Comment by aschempp** [comment]
Follow-up information (see #1980) the problem is that the document root in Contao 3.5 backend is `.../contao` and not `TL_ROOT`.
