### ISSUE TITLE
deserialize error on do=iso_products in Contao 2.11.17

### ISSUE THREAD

**Issue by Aybee** [isotope/core#1130]
isotope     1.4.8 stable    4
Contao 2.11.17

On /contao/main.php?do=iso_products it throws this error

```
Warning: The deserialize() function does not allow serialized objects in …/system/functions.php on line 395

#0 [internal function]: __error(512, 'The deserialize...', '/home/thetha8/p...', 395, Array)
#1 …/system/functions.php(395): trigger_error('The deserialize...', 512)
#2 …/system/drivers/DC_Table.php(4728): deserialize('O:15:"DB_Mysql_...')
#3 …/system/drivers/DC_ProductData.php(2150): DC_Table->filterMenu()
#4 …/system/drivers/DC_ProductData.php(146): DC_ProductData->panel()
#5 …/system/modules/backend/Backend.php(287): DC_ProductData->showAll()
#6 …/contao/main.php(120): Backend->getBackendModule('iso_products')
#7 …/contao/main.php(230): Main->run()
#8 {main}
```

**Comment by kubjo** [comment]
Kann mir jemand erklären, wie ich den patch einspiele?
Danke!

Grüße aus Ludwigsburg
Jochen Kubik
