### ISSUE TITLE
2.2.0-rc1: Warning bei Cumulativen Filter im FE

### ISSUE THREAD

**Issue by xantippe** [isotope/core#1319]
auf Contao 3.3.6

```
Warning: Invalid argument supplied for foreach() in system/modules/isotope/library/Isotope/Module/CumulativeFilter.php on line 126

#0 system/modules/isotope/library/Isotope/Module/CumulativeFilter.php(126): __error(2, 'Invalid argumen...', '/homepages/17/d...', 126, Array)
#1 system/modules/isotope/library/Isotope/Module/CumulativeFilter.php(105): Isotope\Module\CumulativeFilter->generateFilter()
...
```

**Comment by aschempp** [comment]
The solution will be to disable filtering on attributes that have options set in the product.
