### ISSUE TITLE
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'uniqid' in 'where clause' 

### ISSUE THREAD

**Issue by laRocca** [isotope/core#1554]
Hallo,

hab diesmal nen richtigen Vollfehler in meinem [Isotope Shop (Version 2.3.1):](http://webshop2.reindesign.net/cremant-secco.html)

> Fatal error: Uncaught exception Exception with message Query error: Unknown column 'uniqid' in 'where clause' (SELECT tl_iso_productcache.* FROM tl_iso_productcache WHERE uniqid='48e3ba8687fc05c68deeb41838b87a10' AND (keywords='' OR keywords='') AND (expires>1444830706 OR expires=0) AND groups='' LIMIT 0,1) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

> #0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/core/library/Contao/Model.php(1082): Contao\Database\Statement->execute(Array)
#2 system/modules/core/library/Contao/Model.php(923): Contao\Model::find(Array)
#3 system/modules/isotope/library/Isotope/Model/ProductCache.php(89): Contao\Model::findOneBy(Array, Array, Array)
#4 system/modules/isotope/library/Isotope/Module/ProductList.php(140): Isotope\Model\ProductCache::findByUniqid('48e3ba8687fc05c...')
#5 system/modules/core/modules/Module.php(282): Isotope\Module\ProductList->compile()
#6 system/modules/isotope/library/Isotope/Module/Module.php(112): Contao\Module->generate()
#7 system/modules/isotope/library/Isotope/Module/ProductList.php(114): Isotope\Module\Module->generate()
#8 system/modules/core/elements/ContentModule.php(59): Isotope\Module\ProductList->generate()
#9 system/modules/core/library/Contao/Controller.php(476): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}

Was kann ich machen?

**Comment by laRocca** [comment]
Repaired Isotope in the Extension Repository and now it works again.. unfortunately I am afraid I really have a recurrent error in my system and I don't find the source… :-(
