### ISSUE TITLE
[2.3.5 RC Build 6] mod_iso_productlist nicht im dafür vorgesehenen Ordner

### ISSUE THREAD

**Issue by akroii** [isotope/core#1727]
```
[19-Oct-2016 14:12:08 Europe/Berlin] PHP Fatal error: Uncaught exception 'Exception' with message 'Could not find template "mod_iso_productlist_megamenu"' thrown in xxx/xxx/xxx/system/modules/core/library/Contao/TemplateLoader.php on line 123
#0 xxx/xxx/xxx/system/modules/core/library/Contao/Controller.php(76): Contao\TemplateLoader::getPath('mod_iso_product...', 'html5')
#1 xxx/xxx/xxx/system/modules/core/library/Contao/BaseTemplate.php(81): Contao\Controller::getTemplate('mod_iso_product...', 'html5')
#2 xxx/xxx/xxx/system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#3 xxx/xxx/xxx/system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#4 xxx/xxx/xxx/system/modules/core/modules/Module.php(311): Contao\FrontendTemplate->parse()
#5 xxx/xxx/xxx/system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(45): Contao\Module->generate()
#6 xxx/xxx/xxx/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#7 xxx/xxx/xxx/system/modules/isotope/library/Isotope/Module/ProductList.php(111): Isotope\Module\Module->generate()
#8 xxx/xxx/xxx/system/modules/core/library/Contao/Controller.php(321): Isotope\Module\ProductList->generate()
#9 xxx/xxx/xxx/system/modules/core/library/Contao/InsertTags.php(447): Contao\Controller::getFrontendModule('81')
#10 xxx/xxx/xxx/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('{{insert_module...', true)
#11 xxx/xxx/xxx/templates/megamenu.html5(103): Contao\Controller::replaceInsertTags('{{insert_module...')
#12 xxx/xxx/xxx/system/modules/core/library/Contao/InsertTags.php(1113): include('/homepages/10/d...')
#13 xxx/xxx/xxx/system/modules/core/library/Contao/Controller.php(692): Contao\InsertTags->replace('<!DOCTYPE html>...', false)
#14 xxx/xxx/xxx/system/modules/core/controllers/FrontendIndex.php(477): Contao\Controller::replaceInsertTags('<!DOCTYPE html>...', false)
#15 xxx/xxx/xxx/system/modules/core/controllers/FrontendIndex.php(28): Contao\FrontendIndex->outputFromCache()
#16 xxx/xxx/xxx/index.php(19): Contao\FrontendIndex->__construct()
#17 {main}
```

Contao 3.5.15
Wenn man das Template mod_iso_productlist modifiziert und im dafür vorgesehenen Ordner bei [Contao-Root]/templates/frontend ablegt, erhalte ich eine Fehlermeldung, dass genau dieses Template fehlt. Dieses Problem lässt sich umgehen inden man das gleiche Template doppelt bei [Contao-Root]/templates platziert.
Das Modul wird per Inserttag über eine eigene html5 Datei inkludiert.

Ich habe festgestellt, dass dieses Problem auch schon in früheren Isotope Versionen auftritt.

**Comment by aschempp** [comment]
was meinst du mit *dafür vorgesehenen Ordner*? Hast du den im Theme oder Shop-Config zugewiesen?

**Comment by akroii** [comment]
Ich kann festlegen wo sich die ganzen FE-Templates befinden. In meinem Fall bei [Root]/templates/frontend

"/frontend" ist der "dafür vorgesehene Ordner". Das ist im Theme und in der Shop-Config festgelegt.

**Comment by aschempp** [comment]
Ich kann dieses Problem nicht reproduzieren, kannst du vielleicht einen Entwickler auf dein System ansetzen der das im Code nachvollziehen kann?

**Comment by aschempp** [comment]
Ich schliesse dieses Ticket bis wir weitere Informationen haben. Dann gerne wieder öffnen!

**Comment by akroii** [comment]
Ich konnte das Problem jetzt nocheinmal nachstellen. Ich bin mir aber unsicher wo ich das Ticket zuordnen soll.
[#8658](https://github.com/contao/core/issues/8658)

**Comment by aschempp** [comment]
Es ist eine "known limitation" von Contao. Isotope hat darauf keinen Einfluss, und in Contao ist es wohl nicht einfach änderbar.

**Comment by akroii** [comment]
Danke! Zumindest wissen wir jetzt woran es liegt.
