### ISSUE TITLE
EU-Ust-IdNr-Validierung legt Frontend lahm, wenn EU-Server spinnt

### ISSUE THREAD

**Issue by michelbalzer** [isotope/core#1755]
Da der EU-Validierungsserver gerade nicht will, habe ich durch die aktivierte Option „Validierung der USt-IdNr.“ in den Shop-Einstellungen folgende Fehlermeldung – bei Ansicht einer Produktliste im Frontend – erhalten (bei deaktiviertem „Fehlermeldungen anzeigen“ hatte ich dann einfach die be_error.html5):

```
Warning: SoapClient::SoapClient(http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/VatNoValidator/EuViesValidator.php on line 46
#0 [internal function]: __error(2, 'SoapClient::Soa...', '/XXX/XXXX_...', 46, Array)
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/VatNoValidator/EuViesValidator.php(46): SoapClient->SoapClient('http://ec.europ...')
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TaxRate.php(140): Isotope\VatNoValidator\EuViesValidator->__construct()
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TaxClass.php(122): Isotope\Model\TaxRate->isApplicable(5.5, Array)
#4 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TaxClass.php(74): Isotope\Model\TaxClass->calculateGrossPrice(5.5, Array)
#5 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Isotope.php(266): Isotope\Model\TaxClass->calculatePrice(5.5, Array)
#6 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductPrice.php(77): Isotope\Isotope::calculatePrice('5.50', Object(Isotope\Model\ProductPrice), 'price', '1', NULL, Array)
#7 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductPrice.php(205): Isotope\Model\ProductPrice->getAmount(1, Array)
#8 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Collection/ProductPrice.php(167): Isotope\Model\ProductPrice->generate(false, 1, Array)
#9 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php(452): Isotope\Collection\ProductPrice->generate(false, 1, Array)
#10 [internal function]: Isotope\Model\Product\Standard->Isotope\Model\Product\{closure}()
#11 system/modules/core/library/Contao/Template.php(152): call_user_func_array(Object(Closure), Array)
#12 templates/fastbike/iso_list_default.html5(15): Contao\Template->__call('generatePrice', Array)
#13 templates/fastbike/iso_list_default.html5(15): Isotope\Template->generatePrice()
#14 system/modules/core/library/Contao/BaseTemplate.php(88): include('/XXX/XXXX_...')
#15 system/modules/core/library/Contao/Template.php(277): Contao\BaseTemplate->parse()
#16 system/modules/core/classes/FrontendTemplate.php(46): Contao\Template->parse()
#17 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Product/Standard.php(551): Contao\FrontendTemplate->parse()
#18 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductList.php(250): Isotope\Model\Product\Standard->generate(Array)
#19 system/modules/core/modules/Module.php(287): Isotope\Module\ProductList->compile()
#20 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#21 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#22 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/ProductList.php(93): Isotope\Module\Module->generate()
#23 system/modules/core/library/Contao/Controller.php(321): Isotope\Module\ProductList->generate()
#24 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule(Object(Contao\ModuleModel), 'main')
#25 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#26 index.php(20): Contao\FrontendIndex->run()
#27 {main}
```

Geht das weniger radikal zu lösen? Interner Timeout?

**composer.json**
```
{
    "name": "local/website",
    "description": "A website project",
    "type": "project",
    "license": "proprietary",
    "require": {
        "bugbuster/easyupdate3": ">=3.4.0.0,<3.5-dev",
        "bugbuster/tivoka": ">=1.1.0.0,<1.2-dev",
        "cliffparnitzky/birthday-mailer": "1.3.x-dev",
        "cliffparnitzky/user-member-bridge": ">=1.2.2.0,<1.3-dev",
        "comolo/contao-supertheme": "2.3.1.0",
        "contao-community-alliance/composer-client": "~0.12",
        "contao-community-alliance/dc-general": ">=2.0.0.0-beta38,<2.1-dev@beta",
        "contao-legacy/e-spin_dcaconfig-editor": ">=1.0.0.9008,<1.1-dev",
        "contao-legacy/frontend_editor": ">=2.2.6.9003,<2.3-dev",
        "contao-legacy/simple_columns": ">=1.6.2.9002,<1.7-dev",
        "friends-of-contao/contao-associategroups": ">=1.3.1.0,<1.4-dev",
        "isotope/isotope-core": ">=2.4.0.0,<2.5-dev",
        "menatwork/semantic_html5": ">=1.2.0.0,<1.3-dev",
        "metamodels/bundle_all": ">=2.0.0.0,<2.1-dev",
        "phpoffice/phpexcel": ">=1.8.1.0,<1.9-dev",
        "symfony/dependency-injection": ">=2.8.11.0,<2.9-dev",
        "symfony/http-kernel": ">=2.8.11.0,<2.9-dev",
        "terminal42/contao-fineuploader": ">=2.0.0.0,<2.1-dev",
        "terminal42/contao-mailusername": ">=1.0.5.0,<1.1-dev",
        "terminal42/contao-pageimage": ">=3.3.0.0,<3.4-dev"
    },
    "prefer-stable": true,
    "minimum-stability": "dev",
    "config": {
        "preferred-install": "dist",
        "cache-dir": "cache",
        "component-dir": "../assets/components"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        },
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        }
    ],
    "extra": {
        "contao": {
            "migrated": "done",
            "version-locks": {
                "comolo/contao-supertheme": ">=2.3.1.0,<2.4-dev"
            }
        }
    }
}
```

**Comment by aschempp** [comment]
Improved in 8f3caf9097ddf99812779ddd22c7e51d8c138d1d
