### ISSUE TITLE
[2.4.0] Warning: Illegal string offset 'files' 

### ISSUE THREAD

**Issue by akroii** [isotope/core#1776]
Wenn man ein Bild per "Mehrere bearbeiten"->Überschreiben setzen will. Erscheint folgende Fehlermeldung:
```
Warning: Illegal string offset 'files' in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php on line 256
#0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php(256): __error(2, 'Illegal string ...', '/Users/xxx...', 256, Array)
#1 system/modules/core/library/Contao/Widget.php(684): Isotope\Widget\MediaManager->generate()
#2 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#3 system/modules/core/library/Contao/BaseTemplate.php(88): include('/Users/xxx...')
#4 system/modules/core/library/Contao/Widget.php(630): Contao\BaseTemplate->parse()
#5 system/modules/core/classes/DataContainer.php(557): Contao\Widget->parse()
#6 composer/vendor/isotope/isotope-core/system/modules/isotope/drivers/DC_ProductData.php(1008): Contao\DataContainer->row()
#7 system/modules/core/classes/Backend.php(650): DC_ProductData->overrideAll()
#8 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#9 contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```

Schritte zum simulieren der Fehlermeldung:
2 Produkte anwählen -> Überschreiben -> Bilder

**Comment by michelbalzer** [comment]
Hinweis: die Bilder werden aber trotzdem gespeichert und zugewiesen. (auch eben drüber gestolpert)

**Comment by aschempp** [comment]
Fixed in 7997ee64b96d792ed6bb8e3aba29cf4b3f4e4007
