### ISSUE TITLE
DB-Error on attribute creation

### ISSUE THREAD

**Issue by tbd-rsm** [isotope/core#1802]
Hello,

My isotope shop throws an error on attribute creation when adding too many of them. The problem seems to be [MySQL's default limit (64) for KEYs in a table](https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html). This applies only for attributes that generate KEYs for their columns. (e.g. select menus with option "Durchsuchbar im Frontend" set)

```
Fatal error: Uncaught exception Exception with message Query error: Too many keys specified; max 64 keys allowed (ALTER TABLE `tl_iso_product` ADD KEY `foo` (`foo`);) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295
#0 system/modules/core/library/Contao/Database.php(207): Contao\Database\Statement->query('ALTER TABLE `tl...')
#1 system/modules/isotope/library/Isotope/DatabaseUpdater.php(56): Contao\Database->query('ALTER TABLE `tl...')
#2 system/modules/isotope/library/Isotope/Backend/Attribute/Callback.php(103): Isotope\DatabaseUpdater->autoUpdateTables(Array)
#3 system/modules/core/drivers/DC_Table.php(2052): Isotope\Backend\Attribute\Callback->updateDatabase(Object(Contao\DC_Table))
#4 system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(223): Contao\DC_Table->edit()
#5 system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php(69): Isotope\BackendModule\BackendOverview->getModule('attributes')
#6 system/modules/core/classes/Backend.php(423): Isotope\BackendModule\BackendOverview->generate()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('iso_setup')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

This happens when the limit has been reached and isotope wants to add another key on updating tables.

The shop has many different product types/groups (e.g. relais, switches, fuses), each with different sets of relevant technical properties. The frontend product lists can be filtered by those attributes to quickly find the products you need.

- Can i somehow disable KEY creation for those fields or does that lead to other problems (except slower database queries on those fields)?
- Is there another solution or workaround?
- Is isotope the wrong choice for that type of shop?

Thanks, especially for providing that extension.

Regards,
Tobias

**Comment by aschempp** [comment]
I guess that's a bug 😞

**Comment by tbd-rsm** [comment]
Let me know if you need further information on this.

**Comment by aschempp** [comment]
/cc @isotope/developers any ideas? I can see two things:

 1. Only generate indexes for the first 64 (or whatever's available) attributes. Later ones are ignored, the user will never notice…
 2. Have a checkbox to "disable keys". If more than 64 key-able attributes are generated, that field will get an error that it must be enabled. This way the user can enable it on "irrelevant" attributes and control the behavior.

The disadvantage of 2 is that it's way more complex and unnecessary for 99% of users…

**Comment by qzminski** [comment]
2. for me

**Comment by Toflar** [comment]
Yeah 2nd for 2.5 though
