### ISSUE TITLE
Exception in post sale request does not log actual exception

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#1833]
* Contao 4.4.2
* Isotope 2.4.3

I just tested a payment and the postsale request made a log entry saying 
```
Exception in post-sale request. See system/logs/isotope_postsale.log for details.
```
However, when I look into the log file, there is no visible exception there:
```
[31-Jul-2017 13:21:26] New request to https://[…]/system/modules/isotope/postsale.php?mod=pay&id=[…].

Headers: array (
  […],
)

$_GET: array (
  'mod' => 'pay',
  'id' => […],
)

$_POST: array (
  […]
)

Body:
[…]

[31-Jul-2017 13:21:26] Exception in post-sale request
#0 /[…]/vendor/isotope/isotope-core/system/modules/isotope/postsale.php(166): Haste\Http\Response\Response->send()
#1 /[…]/vendor/isotope/isotope-core/system/modules/isotope/postsale.php(240): Isotope\PostSale->run()
#2 {main}
```
Looking at the [log mechanic](https://github.com/isotope/core/blob/master/system/modules/isotope/postsale.php#L180-L186), it looks like it's omitting the actual error:
```php
log_message(
    sprintf(
        "Exception in post-sale request\n%s\n\n",
        $e->getTraceAsString()
    ),
    'isotope_postsale.log'
);
```
`getTraceAsString()` does not include the actual error. The function should probably be changed to:
```php
log_message(
    sprintf(
        "Exception in post-sale request\n%s\n%s\n\n",
        $e->getMessage(),
        $e->getTraceAsString()
    ),
    'isotope_postsale.log'
);
```
Also the `System::log` mechanic seems odd:
```php
\System::log(
    sprintf(
        'Exception in post-sale request. See system/logs/isotope_postsale.log for details.',
        $e->getFile(),
        $e->getLine(),
        $e->getMessage()
    ),
    __METHOD__,
    TL_ERROR
);
```
`sprintf` is used with 3 arguments (the error file, line and message), but there is no placeholder for them in the string.

**Comment by aschempp** [comment]
see #1838
