### ISSUE TITLE
Product collection is locked on paying with Paypal

### ISSUE THREAD

**Issue by pet21221** [isotope/core#1848]
If i want to pay with Paypal, i get this exception: (With Cash-Paying i doesnt have Problems)

`
Fatal error: Uncaught exception BadMethodCallException with message Product collection is locked thrown in system/modules/isotope/library/Isotope/Model/ProductCollection.php on line 1789
#0 system/modules/isotope/library/Isotope/Model/ProductCollection.php(681): Isotope\Model\ProductCollection->ensureNotLocked()
#1 system/modules/isotope/library/Isotope/Module/Checkout.php(234): Isotope\Model\ProductCollection->lock()
#2 system/modules/core/modules/Module.php(287): Isotope\Module\Checkout->compile()
#3 system/modules/haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#4 system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#5 system/modules/isotope/library/Isotope/Module/Checkout.php(109): Isotope\Module\Module->generate()
#6 system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
#7 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#8 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'Mitte')
#9 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'Mitte')
#13 system/modules/core/pages/PageRegular.php(137): Contao\Controller::getFrontendModule('0', 'Mitte')
#14 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}`

**Comment by pet21221** [comment]
Okay, the problem was: I had two Checkout-Module's on the same page.
