### ISSUE TITLE
Productlist sorting, filter: "Warning: Creating default object from empty value"

### ISSUE THREAD

**Issue by GMTeams** [isotope/core#1891]
Since a few hours I get the following error when I'm trying to sort or filter the product list:

`Warning: Creating default object from empty value in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Isotope.php on line 85 #0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Isotope.php(85): __error(2, 'Creating defaul...', '/kunden/12345_...', 85, Array)
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Isotope.php(153): Isotope\Isotope::initialize()
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend/Member/Callback.php(27): Isotope\Isotope::getConfig()
#3 system/modules/core/library/Contao/DcaLoader.php(102): Isotope\Backend\Member\Callback->limitCountries('tl_member')
#4 composer/vendor/codefog/contao-haste/library/Haste/Model/Relations.php(488): Contao\DcaLoader->load()
#5 system/modules/core/library/Contao/Database/Installer.php(410): Haste\Model\Relations->addRelationTables(Array)
#6 system/modules/core/library/Contao/DcaExtractor.php(429): Contao\Database\Installer->getFromFile()
#7 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#8 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_iso_attribut...')
#9 system/modules/core/library/Contao/Model/QueryBuilder.php(32): Contao\DcaExtractor::getInstance('tl_iso_attribut...')
#10 system/modules/core/library/Contao/Model.php(1233): Contao\Model\QueryBuilder::find(Array)
#11 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php(363): Contao\Model::buildFindQuery(Array)
#12 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/TypeAgent.php(209): Isotope\Model\TypeAgent::buildQueryString(Array)
#13 system/modules/core/library/Contao/Model.php(988): Isotope\Model\TypeAgent::find(Array)
#14 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/Attribute.php(946): Contao\Model::findAll(Array)
#15 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend/Product/DcaManager.php(114): Isotope\Model\Attribute::findValid()
#16 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend/Product/DcaManager.php(40): Isotope\Backend\Product\DcaManager->addAttributes()
#17 system/modules/core/library/Contao/DcaLoader.php(102): Isotope\Backend\Product\DcaManager->initialize('tl_iso_product')
#18 composer/vendor/codefog/contao-haste/library/Haste/Model/Relations.php(488): Contao\DcaLoader->load()
#19 system/modules/core/library/Contao/Database/Installer.php(410): Haste\Model\Relations->addRelationTables(Array)
#20 system/modules/core/library/Contao/DcaExtractor.php(429): Contao\Database\Installer->getFromFile()
#21 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#22 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_page')
#23 system/modules/core/library/Contao/Model/QueryBuilder.php(32): Contao\DcaExtractor::getInstance('tl_page')
#24 system/modules/core/library/Contao/Model.php(1233): Contao\Model\QueryBuilder::find(Array)
#25 system/modules/core/library/Contao/Model.php(1068): Contao\Model::buildFindQuery(Array)
#26 system/modules/core/library/Contao/Model.php(965): Contao\Model::find(Array)
#27 system/modules/core/models/PageModel.php(521): Contao\Model::findBy(Array, Array, Array)
#28 system/modules/core/controllers/FrontendIndex.php(93): Contao\PageModel::findPublishedByIdOrAlias('test')
#29 index.php(20): Contao\FrontendIndex->run()
#30 {main}`

Worked well in the last days, today I've made some changes, tried to set them back (and lots of other settings), but couldn't figure it out. Also I've made a composer update, but I don't think there was an update in "Isotope" or "haste" packages.

I think the problem has to do with some settings in the attributes or product types. Would be nice if somebody can help me.

**Comment by GMTeams** [comment]
**Finally I could figure it out:**

Problem was coming from "contao-isotope_simple_stockmanagement", when deactivating this extension, the problem is gone.
