### ISSUE TITLE
Fehler im Kassenmodul, wenn Kunde keine Adresse im Adressbuch hinterlegt hat

### ISSUE THREAD

**Issue by sgei** [isotope/core#1985]
Hallo,

Contao: 3.5.36
Isotope: 2.5.5

Wenn sich ein neuer Kunde registriert und etwas bestellen möchte kommt beim Klick auf Kasse folgende Fehlermeldung:

```
Fatal error: Uncaught exception Error with message Call to a member function generate() on null thrown in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/ShippingAddress.php on line 75

#0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(437): Isotope\CheckoutStep\ShippingAddress->review()
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/OrderInfo.php(41): Isotope\Module\Checkout->getCheckoutInfo()
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(308): Isotope\CheckoutStep\OrderInfo->generate()
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(261): Isotope\Module\Checkout->generateSteps(Array)
#4 system/modules/core/modules/Module.php(287): Isotope\Module\Checkout->compile()
#5 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#6 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#7 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(109): Isotope\Module\Module->generate()
#8 system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
#9 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}
```

Ich möchte, dass die Mitgliederadresse als Rechnungsadresse genommen wird, aber die Versandadresse soll änderbar sein.
Das Kassenmodul ist wiefolgt eingestellt:

**Weiterleitung**
**(x)** Weiterleiten zur Bestätigungsseite

**Bestell-Schritte überspringen**
**(x)** Mitglied-Adresse als Rechnungsadresse verwenden, wenn Mitglied angemeldet ist
( ) Rechnungsadresse als Versandadresse verwenden
( ) Bezahlschritt überspringen wenn nur eine Bezahlmethode verfügbar ist
( ) Versandschritt überspringen wenn nur eine Versandmethode verfügbar ist

Wenn ich auch einen Haken bei "Rechnungsadresse als Versandadresse verwenden" setze, dann kommt der Fehler nicht. Allerdings wird dann der Checkout-Schritt übersprungen.

Steffen

**Comment by aschempp** [comment]
Ich kann diesen Fehler bei mir nicht reproduzieren. Hast du irgendwelche Module installiert welche vielleicht Einfluss darauf nehmen?

**Comment by sgei** [comment]
Hallo,

also ich glaube nicht, dass die installierten Module Einfluss haben, aber wer weiß...
Hier ist mal ein Video, das den ganzen Prozess bis zum Fehler zeigt.
Das Video zeigt auch alle installierten Erweiterungen etc.

[http://geier-media.de/upload/isotope_bug-1985.mp4](isotope_bug-1985.mp4)

Ich kann ich auch gern mal Zugang zum Shop geben. Ich verzweifel bald daran.

Steffen

**Comment by sgei** [comment]
Hallo Andreas,

ich habe gerade den offiziellen Demoshop von Isotope installiert und den Fehler dort sofort reproduzieren können.

Was habe ich gemacht:

- Demoshop installiert
- auf Composer umgestellt
- Erweiterungen + Contao aktualisiert (Contao 3.5.36 Isotope 2.5.8)
- Modul Registrierung + entsprechende Seite und Artikel angelegt
- Kassenmodul entsprechend eingestellt
- Artikel versucht zu bestellen

Hier ist ein Video vom Bug im Demoshop: [isotope_bug-1985_demoshop.mp4](http://geier-media.de/upload/isotope_bug-1985_demoshop.mp4)

Ich schicke dir mal die Zugangsdaten zum Demoshop per Mail.

Steffen

**Comment by sgei** [comment]
Hallo,

ich habe gerade auf 2.5.9 geupdated - der Fehler besteht leider immernoch!!!

Das Kassenmodul ist wiefolgt eingestellt:

Weiterleitung
(x) Weiterleiten zur Bestätigungsseite

Bestell-Schritte überspringen
(x) Mitglied-Adresse als Rechnungsadresse verwenden, wenn Mitglied angemeldet ist
( ) Rechnungsadresse als Versandadresse verwenden
( ) Bezahlschritt überspringen wenn nur eine Bezahlmethode verfügbar ist
( ) Versandschritt überspringen wenn nur eine Versandmethode verfügbar ist

Wenn sich ein Neukunde registriert und dann im Warenkorb auf Kasse drückt kommt wieder die Fehlermeldung:


Fatal error: Uncaught exception Error with message Call to a member function generate() on null thrown in composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/ShippingAddress.php on line 75

#0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(442): Isotope\CheckoutStep\ShippingAddress->review()
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/OrderInfo.php(41): Isotope\Module\Checkout->getCheckoutInfo()
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(311): Isotope\CheckoutStep\OrderInfo->generate()
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(264): Isotope\Module\Checkout->generateSteps(Array)
#4 system/modules/core/modules/Module.php(287): Isotope\Module\Checkout->compile()
#5 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52): Contao\Module->generate()
#6 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111): Haste\Frontend\AbstractFrontendModule->generate()
#7 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(111): Isotope\Module\Module->generate()
#8 system/modules/core/elements/ContentModule.php(59): Isotope\Module\Checkout->generate()
#9 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#11 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#15 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}

Steffen

**Comment by sgei** [comment]
Hallo,

ich habe gerade auf 2.5.9 geupdated - der Fehler besteht leider immer
noch!!!

Das Kassenmodul ist wiefolgt eingestellt:

Weiterleitung
(x) Weiterleiten zur Bestätigungsseite

Bestell-Schritte überspringen
(x) Mitglied-Adresse als Rechnungsadresse verwenden, wenn Mitglied
angemeldet ist
( ) Rechnungsadresse als Versandadresse verwenden
( ) Bezahlschritt überspringen wenn nur eine Bezahlmethode verfügbar ist
( ) Versandschritt überspringen wenn nur eine Versandmethode verfügbar ist

Wenn sich ein Neukunde registriert und dann im Warenkorb auf Kasse drückt
kommt wieder die Fehlermeldung:

Fatal error: Uncaught exception Error with message Call to a member
function generate() on null thrown in
composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/ShippingAddress.php
on line 75

#0 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(442):
Isotope\CheckoutStep\ShippingAddress->review()
#1 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/CheckoutStep/OrderInfo.php(41):
Isotope\Module\Checkout->getCheckoutInfo()
#2 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(311):
Isotope\CheckoutStep\OrderInfo->generate()
#3 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(264):
Isotope\Module\Checkout->generateSteps(Array)
#4 system/modules/core/modules/Module.php(287):
Isotope\Module\Checkout->compile()
#5 composer/vendor/codefog/contao-haste/library/Haste/Frontend/AbstractFrontendModule.php(52):
Contao\Module->generate()
#6 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Module.php(111):
Haste\Frontend\AbstractFrontendModule->generate()
#7 composer/vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Module/Checkout.php(111):
Isotope\Module\Module->generate()
#8 system/modules/core/elements/ContentModule.php(59):
Isotope\Module\Checkout->generate()
#9 system/modules/core/library/Contao/Controller.php(484):
Contao\ContentModule->generate()
#10 system/modules/core/modules/ModuleArticle.php(213):
Contao\Controller::getContentElement(Object(Contao\ContentModel),
'main')
#11 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#12 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#13 system/modules/core/library/Contao/Controller.php(417):
Contao\ModuleArticle->generate(false)
#14 system/modules/core/library/Contao/Controller.php(277):
Contao\Controller::getArticle(Object(Contao\ArticleModel), false,
false, 'main')
#15 system/modules/core/pages/PageRegular.php(133):
Contao\Controller::getFrontendModule('0', 'main')
#16 system/modules/core/controllers/FrontendIndex.php(285):
Contao\PageRegular->generate(Object(Contao\PageModel), true)
#17 index.php(20): Contao\FrontendIndex->run()
#18 {main}

Steffen

Am Do., 15. Nov. 2018 um 02:27 Uhr schrieb Andreas Schempp <
notifications@github.com>:

**Comment by sgei** [comment]
Hallo,

ich habe mir nochmal die Mühe gemacht und unterschiedliche Fälle getestet.

Grundvorraussetzung bei allen Testfällen:
- Neukundenregistrierung
- Tabellen: tl_iso_product_collection, tl_iso_address vor jeden Test geleert

Folgende Einstellungen im Kassenmodul habe ich variiert:
![versuche](https://user-images.githubusercontent.com/2803995/48556034-0857eb80-e8e3-11e8-9d80-23ffc1f2cc84.jpg)

Der Fehler tritt nur auf, wenn das Kassenmodul ist wiefolgt eingestellt ist:

Weiterleitung
(x) Weiterleiten zur Bestätigungsseite

Bestell-Schritte überspringen
(x) Mitglied-Adresse als Rechnungsadresse verwenden, wenn Mitglied angemeldet ist
( ) Rechnungsadresse als Versandadresse verwenden
( ) Bezahlschritt überspringen wenn nur eine Bezahlmethode verfügbar ist
( ) Versandschritt überspringen wenn nur eine Versandmethode verfügbar ist

Hier ist ein Auszug aus der DB - tl_iso_product_collection wenn der Kunde nach Registrierung etwas in den Warenkorb gelegt hat:

![cart_db](https://user-images.githubusercontent.com/2803995/48556139-5d93fd00-e8e3-11e8-96b6-13f2174b3241.jpg)

Hier ist ein Auszug aus der DB - tl_iso_product_collection wenn der Kunde nach Registrierung etwas in den Warenkorb gelegt hat und anschließend auf "Zur Kasse" klickt:

![order_db](https://user-images.githubusercontent.com/2803995/48556176-7dc3bc00-e8e3-11e8-8df0-471f3a13b283.jpg)

Braucht ihr noch mehr Infos?

Steffen
