### ISSUE TITLE
Exception when saving a Product (When versioning is active)

### ISSUE THREAD

**Issue by Guave-Mattias** [isotope/core#2018]
I'm experiencing an Exception when I try to edit the categories of a product. When saving I get the following error:

```
Fatal error: Uncaught exception Error with message Cannot use object of type Isotope\Model\ProductCategory as array thrown in system\modules\isotope\library\Isotope\Backend\Product\Category.php on line 71
#0 [internal function]: Isotope\Backend\Product\Category->Isotope\Backend\Product\{closure}(Object(Isotope\Model\ProductCategory))
#1 system\modules\isotope\library\Isotope\Backend\Product\Category.php(72): array_map(Object(Closure), Array)
#2 system\modules\isotope\drivers\DC_ProductData.php(762): Isotope\Backend\Product\Category->createVersion('tl_iso_product', '4', Object(DC_ProductData))
#3 system\modules\core\classes\Backend.php(650): DC_ProductData->edit()
#4 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('iso_products')
#5 contao\main.php(20): Contao\BackendMain->run()
#6 {main}
```

Checking the sourcode I see that on the following line the list of the current categories is queried:

https://github.com/isotope/core/blob/e95d8b26c4c14ae31f1e2c692a3a69785f80ca17/system/modules/isotope/library/Isotope/Backend/Product/Category.php#L57

That call returns a collection of models. Those are then later mapped to the ID here:

https://github.com/isotope/core/blob/e95d8b26c4c14ae31f1e2c692a3a69785f80ca17/system/modules/isotope/library/Isotope/Backend/Product/Category.php#L71

But since we're working with a list of models, we can't access the ID like that. The line should read:

`return $category->id`

The same problem occurs on this line:

https://github.com/isotope/core/blob/e95d8b26c4c14ae31f1e2c692a3a69785f80ca17/system/modules/isotope/library/Isotope/Backend/Product/Price.php#L62

Although that one is a little more complex to fix.

**Comment by Guave-Mattias** [comment]
Never mind, it's something on my code :-)
