### ISSUE TITLE
Invalid argument supplied for foreach() during file upload

### ISSUE THREAD

**Issue by fritzmg** [isotope/core#2070]
Sentry just reported the following error to me:
```
ErrorException: Invalid argument supplied for foreach()
#20 vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php(153): handleError
#19 vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php(153): validateUpload
#18 vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Widget/MediaManager.php(89): ajaxUpload
#17 vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Backend.php(334): executePostActions
#16 vendor/contao/core-bundle/src/Resources/contao/classes/Ajax.php(456): executePostActionsHook
#15 vendor/contao/core-bundle/src/Resources/contao/classes/Ajax.php(439): executePostActions
#14 vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php(413): getBackendModule
#13 vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php(169): run
#12 vendor/contao/core-bundle/src/Controller/BackendController.php(48): mainAction
#11 vendor/symfony/http-kernel/HttpKernel.php(150): handleRaw
#10 vendor/symfony/http-kernel/HttpKernel.php(67): handle
#9 vendor/symfony/http-kernel/Kernel.php(198): handle
#8 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): handle
#7 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): forward
#6 vendor/symfony/framework-bundle/HttpCache/HttpCache.php(57): forward
#5 vendor/symfony/http-kernel/HttpCache/HttpCache.php(238): pass
#4 vendor/symfony/http-kernel/HttpCache/HttpCache.php(255): invalidate
#3 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(126): invalidate
#2 vendor/symfony/http-kernel/HttpCache/HttpCache.php(181): handle
#1 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): handle
#0 web/app.php(58): null
```
The error occurs here:

https://github.com/isotope/core/blob/9265ce556c3b3e5e0ea8ecbb1f95a0d7892ce449/system/modules/isotope/library/Isotope/Widget/MediaManager.php#L152-L156

`$_SESSION['TL_ERROR']` does not exist in Contao 4 (4.7.7 in this case) any more. I am assuming you are trying to access messages added via `Message::add` here? Since that is where those messages used to be stored in Contao 3:

https://github.com/contao/core/blob/e38d7e62fef58a73bfcd7a96fe6f303073808d01/system/modules/core/library/Contao/Message.php#L87-L113

But not any more in Contao 4: 

https://github.com/contao/contao/blob/6c4feeeeed5314242a644b7507eaefafb8eb69d8/core-bundle/src/Resources/contao/library/Contao/Message.php#L86-L108

**Comment by aschempp** [comment]
Der Fehler ist in der 2.6.2 behoben.
