### ISSUE TITLE
Warning: Attempt to read property "member" on null while running cron

### ISSUE THREAD

**Issue by ameotoko** [isotope/core#2350]
I disabled module "Rules" as Integrity check told me to. Shouldn't all related hooks be skipped then?

```
ErrorException: Warning: Attempt to read property "member" on null
#22 /vendor/isotope/isotope-core/system/modules/isotope_rules/library/Isotope/Rules.php(50): Isotope\Rules::__construct
#21 /vendor/isotope/isotope-core/system/modules/isotope_rules/library/Isotope/Rules.php(63): Isotope\Rules::getInstance
#20 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php(272): Contao\System::importStatic
#19 /vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Model/ProductCollection.php(689): Isotope\Model\ProductCollection::delete
#18 /vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Automator.php(195): Isotope\Automator::deleteOldCollections
#17 /vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/Automator.php(43): Isotope\Automator::deleteOldCarts
#16 /vendor/contao/core-bundle/src/Cron/LegacyCron.php(87): Contao\CoreBundle\Cron\LegacyCron::runLegacyCrons
#15 /vendor/contao/core-bundle/src/Cron/LegacyCron.php(49): Contao\CoreBundle\Cron\LegacyCron::onDaily
#14 /vendor/contao/core-bundle/src/Cron/CronJob.php(43): Contao\CoreBundle\Cron\CronJob::__invoke
#13 /vendor/contao/core-bundle/src/Cron/Cron.php(126): Contao\CoreBundle\Cron\Cron::run
#12 /vendor/contao/core-bundle/src/Controller/FrontendController.php(49): Contao\CoreBundle\Controller\FrontendController::cronAction
#11 /vendor/symfony/http-kernel/HttpKernel.php(152): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#10 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel::handle
#9 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#8 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#7 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#6 /vendor/symfony/framework-bundle/HttpCache/HttpCache.php(73): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward
#5 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Symfony\Component\HttpKernel\HttpCache\HttpCache::fetch
#4 /vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(66): Contao\ManagerBundle\HttpKernel\ContaoCache::fetch
#3 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache::lookup
#2 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#1 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): Contao\ManagerBundle\HttpKernel\ContaoCache::handle
#0 /public/index.php(44): null
```

**Comment by aschempp** [comment]
hmm, did you clear the application cache? maybe the hook config still existed in the cache

**Comment by ameotoko** [comment]
Sorry, it's my fault – not only was it in the cache, but it was not even disabled 🤦🏻‍♂️

I was testing a different problem with this (see below), and forgot to leave it disabled in the end.

I currently have an issue with this legacy feature – when Isotope disables the module from the back end, Contao fails on first reload, because cache is cleared incorrectly. I don't even know whether it can or should be fixed? Should I describe the details in a separate issue?

**Comment by aschempp** [comment]
I think a separate issue would be best. Also not sure if it can be fixed, truncating the cache at runtime is not really supported by Symfony I guess 😆

**Comment by ameotoko** [comment]
Aha, I get it now, it wasn't actually my fault. Everything in `vendor` gets overwritten with any update/install (and that's what happens during deployment, for example). I guess, it's still not recommended to edit anything in `vendor/` on a production server 😉

**Comment by aschempp** [comment]
it sure is not! 😂 so the issue can be closed?

**Comment by ameotoko** [comment]
> I guess, it's still not recommended to edit anything in vendor/ on a production server 😉

I meant, of course `.skip` files. Isotope writes them to `vendor/`.

Yes, the issue can be closed, I guess.
